### ISSUE TITLE
2.3.0 - Broken update

### ISSUE THREAD

**Issue by mofman** [craft-snippets/Craft-image-toolbox#25]
Getting all sorts of errors and strange behaviour in this release. 

On my local environment, some images transform on page successfully and are displayed, others seem to transform but dont actually appear on page. Caching appears to be broken upon refreshing the page all images start transforming again.

On staging/live environment, plugin is completely broken - looks to be related to new AVIF functionality.

<img width="1087" alt="Screenshot 2024-04-05 at 15 12 00" src="https://github.com/craft-snippets/Craft-image-toolbox/assets/3038169/9ffe5d55-7c1c-473f-87c0-6088abea8de2">

**Comment by piotrpog** [comment]
For now you can disable avif transform by setting `useAvif` in the plugin config to `false`. i will soon release update that disabels avif by default.

Can you tell me if you use transform without image toolbox and set format to avif, do you also get errors? 
What shows up when you put `{{dump(craft.app.images.supportsAvif())}}` in your template?

**Comment by piotrpog** [comment]
The latest update for both craft 4 and craft 5 branches disables default avif generation.
It can still be enabled using `useAvif` config option.
