### ISSUE TITLE
Webp support

### ISSUE THREAD

**Issue by CreateSean** [craft-snippets/Craft-image-toolbox#5]
Locally I am able to see webp images generated. However on my forge/digital ocean server with ubuntu 18.04 webp is not working so I installed webp like this:

```sudo apt install webp```

However that doesn't appear to have worked. as when I add this conditional to my code I get the no webp support

```
  {% if craft.app.images.supportsWebP() %}
    webp support
  {% else %}
    no webp support
  {% endif %}
```

I also checked php info and it shows webp support enabled
![image](https://user-images.githubusercontent.com/6899490/108601290-dbb89700-7369-11eb-9610-1f7f412f67fa.png)

Is there something else I need to do to get webp to work with image-toolbox on my server?

**Comment by piotrpog** [comment]
Image toolbox internally uses [getSupportsWebP](https://docs.craftcms.com/api/v3/craft-services-images.html#method-getsupportswebp) function to check for webp support.

Can you check what `dump(craft.app.images.getSupportsWebP())` will return in Twig?

**Comment by CreateSean** [comment]
Adding that code gave me an internal server error on the live site, but when I changed it to this:

```twig
  {% if craft.app.images.supportsWebP() %}
    webp support
  {% else %}
    no webp support
  {% endif %}
```

it returned no webp support.

However in discord I discovered that other plugins, Image Optimizer and Imager-x support another way to get webp support by adding `cwebp ` to your install. https://discordapp.com/channels/456442477667418113/456448961679589386/812707914174955539

It seems that the reason this isn't working with image-toolbox is that ubuntu 18.04 doesn't support webp so you need to install `cwebp` and ensure that any plugins support that extension.

I checked on another site I have on a ubuntu 20.04 server and webp works as expected.

If you could add in `cwebp` to image-toolbox to support sites on older servers that would be great, but if not, while disappointed I understand.

**Comment by piotrpog** [comment]
@CreateSean 
I think i have idea how your issue can be solved - i will just add option to force usage of webp, even if Craft built in function (erroneously) detect that there is no webp support on server.

**Comment by CreateSean** [comment]
Excellent, looking forward to it. Thanks.

**Comment by piotrpog** [comment]
@CreateSean 
1.1.0 version with `forceWebp` setting was just released.
