### ISSUE TITLE
AssetTransform

### ISSUE THREAD

**Issue by pette87** [craft-snippets/Craft-image-toolbox#6]
Hi,

have following error:

**Setting unknown property: craft\models\AssetTransform::(max-width: 600px)**

                            `{% set hero = block.background.one() %}
                            {% set transforms = {
                                '(max-width: 600px)': {
                                    width: 100,
                                },
                                '(max-width: 999px)': {
                                    width: 400,
                                },
                            } %}

                            {{craft.images.picture(hero, transforms) }}`

**Comment by piotrpog** [comment]
@pette87 
`picture` is used for image without breakpoints. For breakpoints, you can use `pictureMedia`.

```
{{craft.images.pictureMedia(hero, transforms)}}
```

I will redesign functions a bit in the future by the way, so both of these functionalities can be used by single function.

**Comment by pette87** [comment]
Thanks 👍
